### ISSUE TITLE
WEBSITES4 - Create Website List Page

### ISSUE THREAD

**Issue by jannunzi** [jannunzi/wam-ng2#4]
HTML, Angular Material, CSS, Template, Component, Connect to existing web service in Angular 1 Repo

**Comment by rishi11** [comment]
I am able to setup website view, models, services which is able to fetch the data from ng1-server. For now I am hardcoding the developer ID because that I need to pick from local storage when login and register functionalities will be ready. I also setup angular-materials for website view.

**Comment by rishi11** [comment]
Code merged to master. An intermediate profile page is required to complete the flow.
